import SpkBadge from "../../../@spk/uielements/spk-badge";

const DashboardIcon = <i className="bx bx-home side-menu__icon"></i>;

// const PagesIcon = <i className="bx bx-file-blank side-menu__icon"></i>;

// const TaskIcon = <i className="bx bx-task side-menu__icon"></i>;

// const AuthenticationIcon = (
//   <i className="bx bx-fingerprint side-menu__icon"></i>
// );

// const ErrorIcon = <i className="bx bx-error side-menu__icon"></i>;

// const UiElementsIcon = <i className="bx bx-box side-menu__icon"></i>;

// const Utilities = <i className="bx bx-medal side-menu__icon"></i>;

// const FormsIcon = <i className="bx bx-file  side-menu__icon"></i>;

// const AdvancedUiIcon = <i className="bx bx-party side-menu__icon"></i>;

// const WidgetsIcon = <i className="bx bx-gift side-menu__icon"></i>;

// const AppsIcon = <i className="bx bx-grid-alt side-menu__icon"></i>;

// const NestedmenuIcon = <i className="bx bx-layer side-menu__icon"></i>;

// const TablesIcon = <i className="bx bx-table side-menu__icon"></i>;

// const ChartsIcon = <i className="bx bx-bar-chart-square side-menu__icon"></i>;

// const MapsIcon = <i className="bx bx-map side-menu__icon"></i>;

// const Icons = <i className="bx bx-store-alt side-menu__icon"></i>;

const badge = (
  <SpkBadge customClass="!bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-1">
    12
  </SpkBadge>
);
// const badge1 = (
//   <span className="text-secondary text-[0.75em] rounded-sm !py-[0.25rem] !px-[0.45rem] badge !bg-secondary/10 ms-1">
//     New
//   </span>
// );
// const badge2 = (
//   <span className="text-danger text-[0.75em] rounded-sm badge !py-[0.25rem] !px-[0.45rem] !bg-danger/10 ms-1">
//     Hot
//   </span>
// );
// const badge4 = (
//   <span className="text-success text-[0.75em] badge !py-[0.25rem] !px-[0.45rem] rounded-sm bg-success/10 ms-1">
//     3
//   </span>
// );

export const MenuItems: any = [
  {
    menutitle: "MAIN",
  },

  {
    icon: DashboardIcon,
    badgetxt: badge,
    title: "Dashboards",
    type: "sub",
    active: false,
    selected: false,
    children: [
      // {
      //   path: `${import.meta.env.BASE_URL}dashboards/crm`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "CRM",
      // },
      // {
      //   path:`${import.meta.env.BASE_URL}dashboards/ecommerce`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "Ecommerce",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}dashboards/crypto`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "Crypto",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}dashboards/jobs`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "Jobs",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}dashboards/nft`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "NFT",
      // },
      {
        path: `${import.meta.env.BASE_URL}dashboards/corporate`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Analytics",
      },
      // {
      //   path: `${import.meta.env.BASE_URL}dashboards/analytics`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "Analytics",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}dashboards/projects`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "Projects",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}dashboards/hrm`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "HRM",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}dashboards/stocks`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "Stocks",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}dashboards/courses`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "Courses",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}dashboards/personal`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "Personal",
      // },
    ],
  },

  // {
  //   menutitle: "PAGES",
  // },

  // {
  //   icon: PagesIcon,
  //   badgetxt: badge1,
  //   title: "Pages",
  //   type: "sub",
  //   active: false,
  //   selected: false,
  //   children: [
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/about-us`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "About Us",
  //     },
  //     {
  //       title: "Blog",
  //       type: "sub",
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/blog/blog`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Blog",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/blog/blog-details`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Blog-Details",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/blog/create-blog`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Create-Blog",
  //         },
  //       ],
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/chat`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Chat",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/contacts`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Contacts",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/contact-us`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Contact-Us",
  //     },
  //     {
  //       title: "Ecommerce",
  //       type: "sub",
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/ecommerce/add-products`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Add Products",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/ecommerce/cart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Cart",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/ecommerce/checkout`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Checkout",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/ecommerce/edit-products`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Edit Products",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/ecommerce/order-details`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Order Details",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/ecommerce/orders`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Orders",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/ecommerce/products`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Products",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/ecommerce/product-details`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Product Details",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/ecommerce/product-list`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Products List",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/ecommerce/wishlist`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Wishlist",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Email",
  //       type: "sub",
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/email/mail-app`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Mail-App",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/email/mail-settings`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Mail-Settings",
  //         },
  //       ],
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/empty`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Empty",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/faqs`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "FAQ's",
  //     },
  //     {
  //       title: "File Manager",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/filemanager/filemanager`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "File Manager",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Invoice",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/invoice/create-invoice`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Create Invoice",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/invoice/invoice-details`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Invoice Details",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/invoice/invoice-list`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Invoice List",
  //         },
  //       ],
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/landing`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Landing",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/jobs-landing`,
  //       badgetxt: badge1,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Jobs Landing",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/notifications`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Notifications",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/pricing`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Pricing",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/profile`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Profile",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/reviews`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Reviews",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/team`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Team",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/terms-conditions`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Terms & Conditions",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/timeline`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Timeline",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}pages/todo-list`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "To Do List",
  //     },
  //   ],
  // },
  // {
  //   icon: TaskIcon,
  //   title: "Task",
  //   badgetxt: badge1,
  //   type: "sub",
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   children: [
  //     {
  //       path: `${import.meta.env.BASE_URL}task/kanban-board`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Kanban Board",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}task/list-view`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "List View",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}task/task-details`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Task Details",
  //     },
  //   ],
  // },
  // {
  //   icon: AuthenticationIcon,
  //   title: " Authentication",
  //   type: "sub",
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   children: [
  //     {
  //       path: `${import.meta.env.BASE_URL}authentication/coming-soon`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Coming Soon",
  //     },

  //     {
  //       title: "Create Password",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/create-password/create-basic`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Basic",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/create-password/create-cover`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Cover",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Lock Screen",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/lock-screen/screen-basic`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Basic",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/lock-screen/screen-cover`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Cover",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Reset Password",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/reset-password/reset-basic`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Basic",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/reset-password/reset-cover`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Cover",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Sign Up",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/sign-up/signup-basic`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Basic",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/sign-up/signup-cover`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Cover",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Sign In",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/sign-in/signin-basic`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Basic",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/sign-in/signin-cover`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Cover",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Two Step Verification",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/two-step-verification/two-basic`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Basic",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/two-step-verification/two-cover`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Cover",
  //         },
  //       ],
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}authentication/under-maintanance`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Under Maintainance",
  //     },
  //   ],
  // },
  // {
  //   icon: ErrorIcon,
  //   title: "Error",
  //   type: "sub",
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   children: [
  //     {
  //       path: `${import.meta.env.BASE_URL}error/error-401`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "401-Error",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}error/error-404`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "404-Error",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}error/error-500`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "500-Error",
  //     },
  //   ],
  // },

  // {
  //   menutitle: "GENERAL",
  // },
  // {
  //   title: "Ui Elements",
  //   icon: UiElementsIcon,
  //   type: "sub",
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   children: [
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/alerts`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Alerts",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/badge`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Badge",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/breadcrumb`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Breadcrumb",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/buttons`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Buttons",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/button-group`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Button Group",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/blockquotes`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Blockquotes",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/cards`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Cards",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/dropdowns`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Dropdowns",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/images-figures`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Images & Figures",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/list-group`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "List Group",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/navs-tabs`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Navs & Tabs",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/object-fit`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Object Fit",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/pagination`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Pagination",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/popovers`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Popovers",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/progress`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Progress",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/indicators`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Indicators",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/spinners`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Spinners",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/toasts`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Toasts",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}ui-elements/tooltips`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Tooltips",
  //     },
  //   ],
  // },
  // {
  //   title: "Utilities",
  //   icon: Utilities,
  //   type: "sub",
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   children: [
  //     {
  //       path: `${import.meta.env.BASE_URL}utilities/avatars`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Avatars",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}utilities/borders`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Borders",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}utilities/colors`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Colors",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}utilities/grids`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Grids",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}utilities/flex`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Flex",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}utilities/columns`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Columns",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}utilities/typography`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Typography",
  //     },
  //   ],
  // },
  // {
  //   title: "Forms",
  //   icon: FormsIcon,
  //   type: "sub",
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   children: [
  //     {
  //       title: "Form Elements",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/inputs`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Inputs",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/check-radios`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "checks & Radios ",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/formswitch`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Form switch",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/input-group`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Input Group",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/form-select`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Form select",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/range-slider`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Range Slider",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/file-uploads`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "File Uploads",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/date-time-picker`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Date,Time Picker",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/color-picker`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Color Pickers",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/advancedselect`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Advanced Select",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/inputnumber`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Input Number",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/passwords`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Passwords",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements/countermarkup`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Counters & Markup",
  //         },
  //       ],
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}forms/form-layouts`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Form Layouts",
  //     },
  //     {
  //       title: "Form Editors",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: "forms/formeditors/formeditor",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Sun Editors",
  //         },
  //       ],
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}forms/validation`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Validation",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}forms/select2`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Select2",
  //     },
  //   ],
  // },
  // {
  //   title: "Advanced Ui",
  //   icon: AdvancedUiIcon,
  //   type: "sub",
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   children: [
  //     {
  //       path: `${import.meta.env.BASE_URL}advanced-ui/accordions-collapse`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Accordions & collapse",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}advanced-ui/customscrollbar`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Custom scrollbar",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}advanced-ui/draggable-cards`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Draggable Cards",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}advanced-ui/modals-closes`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Modals & Closes",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}advanced-ui/navbar`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Navbar",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}advanced-ui/offcanvas`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Offcanvas",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}advanced-ui/ratings`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Ratings",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}advanced-ui/swiper-js`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Swiper JS",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}advanced-ui/stepper`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Stepper",
  //     },
  //   ],
  // },
  // {
  //   path: `${import.meta.env.BASE_URL}widgets`,
  //   title: "widgets",
  //   icon: WidgetsIcon,
  //   badgetxt: badge2,
  //   type: "link",
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  // },

  // {
  //   menutitle: "WEB APPS",
  // },
  // {
  //   title: "Apps",
  //   icon: AppsIcon,
  //   type: "sub",
  //   badgetxt: badge1,
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   children: [
  //     {
  //       path: `${import.meta.env.BASE_URL}apps/full-calendar`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Full Calendar",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}apps/gallery`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Gallery",
  //     },
  //     {
  //       title: "Projects",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/projects/project-list`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Project List",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/projects/project-overview`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Project Overview",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/projects/create-project`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Create Project",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Jobs",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/jobs/job-details`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Job Details",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/jobs/search-company`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Search Company",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/jobs/search-jobs`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Search Jobs",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/jobs/job-post`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: " Job Post",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/jobs/jobs-list`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: " Jobs List",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/jobs/search-candidate`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: " Search Candidate",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/jobs/candidate-details`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Candidate details",
  //         },
  //       ],
  //     },
  //     {
  //       title: "NFT",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/nft/market-place`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Market Place",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/nft/nft-details`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "NFT Details",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/nft/create-nft`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Create NFT",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/nft/wallet-integration`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: " Wallet Integration",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/nft/live-auction`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Live Auction",
  //         },
  //       ],
  //     },
  //     {
  //       title: "CRM",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/crm/crmcontacts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Contacts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/crm/companies`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Companies",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/crm/deals`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Deals",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/crm/leads`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: " Leads",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Crypto",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/crypto/transactions`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Transactions",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/crypto/currency-exchange`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Currency Exchanges",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/crypto/buy-sell`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Buy & Sell",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/crypto/market-cap`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: " Marketcap",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/crypto/wallet`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Wallet",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   icon: NestedmenuIcon,
  //   title: "Nested Menu",
  //   selected: false,
  //   active: false,
  //   type: "sub",
  //   children: [
  //     {
  //       path: "",
  //       title: "Nested-1",
  //       type: "empty",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //     },

  //     {
  //       title: "Nested-2",
  //       type: "sub",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: "",
  //           type: "empty",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Nested-2-1",
  //         },
  //         {
  //           path: "",
  //           type: "empty",
  //           ctive: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Nested-2-2",
  //         },
  //         {
  //           path: "",
  //           type: "empty",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Nested-2-3",
  //         },
  //       ],
  //     },
  //   ],
  // },

  // {
  //   menutitle: "TABLES & CHARTS",
  // },
  // {
  //   title: "Tables",
  //   icon: TablesIcon,
  //   type: "sub",
  //   menutitle: "",
  //   badgetxt: badge4,
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   children: [
      // {
      //   path: `${import.meta.env.BASE_URL}tables/table`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "Tables",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}tables/gridjs-table`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false, 
      //   title: "Grid JS Tables",
      // },
    //   {
    //     path: `${import.meta.env.BASE_URL}tables/data-table`,
    //     type: "link",
    //     active: false,
    //     selected: false,
    //     dirchange: false, 
    //     title: "Completed Tranactions",
    //   },
    //   {
    //     path: `${import.meta.env.BASE_URL}tables/data-table`,
    //     type: "link",
    //     active: false,
    //     selected: false,
    //     dirchange: false, 
    //     title: "Failed Tranactions",
    //   },
    // ],
 //},

  // {
  //   title: "Charts",
  //   icon: ChartsIcon,
  //   type: "sub",
  //   selected: false,
  //   active: false,
  //   children: [
  //     {
  //       title: "Apex Charts",
  //       type: "sub",
  //       menusub: true,
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/line-charts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Line Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/area-charts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Area Charts ",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/column-charts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Column Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/bar-charts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Bar Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/mixed-charts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Mixed Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/range-area-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Range Area Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/timeline-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Timeline Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/candlestick-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "CandleStick Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/boxplot-charts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Boxplot Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/bubble-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Bubble Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/scatter-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Scatter Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/heatmap-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Heatmap Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/treemap-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Treemap Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/pie-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Pie Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/radialbar-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Radialbar Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/radar-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Radar Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/polararea-chart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           dirchange: false, 
  //           title: "Polararea Charts",
  //         },
  //       ],
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}charts/chartjs`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "ChartJS Charts",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}charts/echart`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Echart Charts",
  //     },
  //   ],
  // },

  // { menutitle: "MAPS & ICONS" },
  // {
  //   title: "Maps",
  //   icon: MapsIcon,
  //   type: "sub",
  //   background: "hor-rightangle",
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   children: [
  //     {
  //       path: `${import.meta.env.BASE_URL}maps/google-map`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Google Maps",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}maps/leaflet-map`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Leaflet Maps",
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}maps/vector-maps`,
  //       type: "link",
  //       active: false,
  //       selected: false,
  //       dirchange: false, 
  //       title: "Vector Maps",
  //     },
  //   ],
  // },
  // {
  //   path: `${import.meta.env.BASE_URL}icons`,
  //   icon: Icons,
  //   type: "link",
  //   active: false,
  //   selected: false,
  //   dirchange: false, 
  //   title: "Icons",
  // },
];
